# Project 1 - App.vwo.com
url=https://app.vwo.com
qa_url=https://app.vwo.com

url1= https://www.facebook.com/
username1 = contact+aug@thetestingacademy.com
password1=TtxkgQ!s$rJBk85

url2 = https://demoqa.com/modal-dialogs
#text_msg = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
text_msg = Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

url3 = https://www.naukri.com/

username2= sachinmali0891@gmail.com
password2= Dhanashree@123



username=contact+aug@thetestingacademy.com
password=TtxkgQ!s$rJBk85

invalid_username=admin@admin.com
invalid_password=Test@2024

expected_username=Aman
error_message=Your email, password, IP address or location did not match
error_message1=The email address you entered isn't connected to an account. Find your account and log in.
invalid_error_message=Pramod email, password, IP address or location did not match
browser= edge
# Project 2 - Orange HR
ohr_username=admin
ohr_password=Hacker@4321
ohr_expected_username=PIM

# Project 3 - Katalon App
katalon_url=https://katalon-demo-cura.herokuapp.com/